package org.javalens.core.buildsystem;

import org.eclipse.jdt.apt.core.util.AptConfig;
import org.eclipse.jdt.apt.core.util.IFactoryPath;
import org.eclipse.jdt.core.IJavaProject;
import org.eclipse.jdt.core.IType;
import org.javalens.core.JdtServiceImpl;
import org.javalens.core.fixtures.TestEnvironment;
import org.javalens.core.fixtures.TestProjectHelper;
import org.javalens.core.project.model.LoadWarning;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Bug H — annotation processing was never enabled, so symbols generated by processors like
 * Lombok / MapStruct / Dagger / JPA Metamodel were invisible to JDT analysis.
 *
 * <p>The fix wires APT on the {@code IJavaProject}: calls {@link AptConfig#setEnabled} (which
 * transitively sets the {@code COMPILER_PROCESS_ANNOTATIONS} compiler option), builds an
 * {@link IFactoryPath} populated with the processor jars declared in pom
 * {@code <annotationProcessorPaths>}, and registers it via {@link AptConfig#setFactoryPath}.
 *
 * <p>Coverage in this file:
 * <ul>
 *   <li>Positive: copies the {@code lombok-maven} fixture, runs {@code mvn dependency:resolve}
 *       to seed Lombok in {@code ~/.m2}, then asserts (a) APT is enabled, (b) the project has
 *       a project-specific factory path, (c) the lombok jar appears in the factory-path
 *       containers (verified via reflection against the internal {@code FactoryPath} impl —
 *       reflection because {@link IFactoryPath} has no public read API and we don't want the
 *       core bundle to depend on an internal JDT package just for a test assertion), (d) no
 *       {@link LoadWarning#APT_PROCESSOR_JARS_MISSING} was emitted.</li>
 *   <li>Negative: loads {@code simple-maven} (no processors declared) and asserts APT is NOT
 *       enabled, no project-specific factory path was set, no APT warnings surfaced.</li>
 * </ul>
 *
 * <p>The actual generation of Lombok methods inside JDT additionally requires Lombok's Eclipse
 * agent (see deferred-to-1.5.0 item E-9); these tests cover the wiring this code is responsible
 * for, not the agent. Cross-build-system coverage of the SPI-descriptor classpath-scan branch
 * (Bazel) requires a fixture with a real annotation-processor SPI jar — also a future item.
 */
class AnnotationProcessingTest {

    @RegisterExtension
    TestProjectHelper helper = new TestProjectHelper();

    @Test
    @DisplayName("Lombok project: APT enabled, project-specific factory path, lombok jar registered, no missing-jar warning")
    void lombokProject_aptFullyWired() throws Exception {
        String mvn = resolveMavenBinary();
        TestEnvironment.requireOrSkip(mvn,
            "Maven binary (APT wiring needs mvn to seed lombok in ~/.m2)");

        String previousOverride = System.getProperty("javalens.maven.binary");
        System.setProperty("javalens.maven.binary", mvn);
        try {
            Path projectRoot = helper.copyFixture("lombok-maven");
            runMaven(mvn, projectRoot, "dependency:resolve", "-B", "-q");

            JdtServiceImpl service = new JdtServiceImpl();
            service.loadProject(projectRoot);

            IJavaProject javaProject = service.getJavaProject();

            // (a) APT enabled.
            assertTrue(AptConfig.isEnabled(javaProject),
                "AptConfig.isEnabled must be true for a project with declared processors");

            // (b) Project-specific factory path set (proves wireApt called setFactoryPath
            // with our customized path, rather than leaving the workspace default).
            assertTrue(AptConfig.hasProjectSpecificFactoryPath(javaProject),
                "hasProjectSpecificFactoryPath must be true after wireApt registers jars");

            // (c) Lombok jar appears in the factory-path containers. IFactoryPath has no
            // public read API; we use reflection against the internal FactoryPath impl's
            // getAllContainers() rather than add an internal-package import to the core
            // bundle's MANIFEST just for a test. If JDT ever renames either symbol, the
            // reflection lookup fails loudly — the correct alarm for a contract change.
            IFactoryPath factoryPath = AptConfig.getFactoryPath(javaProject);
            assertTrue(factoryPathContainerIds(factoryPath).stream()
                    .anyMatch(id -> id != null && id.toLowerCase().contains("lombok")),
                "Factory path must include the lombok processor jar; container ids: "
                    + factoryPathContainerIds(factoryPath));

            // (d) No APT_PROCESSOR_JARS_MISSING warning — the jar is on disk, the wire
            // succeeded fully, the silent-degradation path must not have fired.
            boolean aptMissingWarning = service.getWarnings().stream()
                .anyMatch(w -> LoadWarning.APT_PROCESSOR_JARS_MISSING.equals(w.code()));
            assertFalse(aptMissingWarning,
                "APT_PROCESSOR_JARS_MISSING must not fire when lombok jar is present; warnings: "
                    + service.getWarnings());

            // Source type resolves (regardless of agent — agent is required for generated
            // members but not for the source class itself).
            IType bean = service.findType("com.example.LombokBean");
            assertNotNull(bean, "LombokBean source type should resolve");
        } finally {
            if (previousOverride == null) System.clearProperty("javalens.maven.binary");
            else System.setProperty("javalens.maven.binary", previousOverride);
        }
    }

    @Test
    @DisplayName("Project with no declared processors: APT not enabled, no project-specific factory path, no APT warnings")
    void noProcessors_aptNotEnabled() throws Exception {
        // simple-maven has no <annotationProcessorPaths>. applyAnnotationProcessing's
        // empty-collection early return must mean wireApt is never called, so APT stays
        // at its default-disabled state and the project never gets a custom factory path.
        Path projectRoot = helper.copyFixture("simple-maven");

        JdtServiceImpl service = new JdtServiceImpl();
        service.loadProject(projectRoot);

        IJavaProject javaProject = service.getJavaProject();

        assertFalse(AptConfig.isEnabled(javaProject),
            "AptConfig.isEnabled must be false for a project with no declared processors");
        assertFalse(AptConfig.hasProjectSpecificFactoryPath(javaProject),
            "No project-specific factory path should be set when wireApt was never called");

        boolean anyAptWarning = service.getWarnings().stream()
            .anyMatch(w -> LoadWarning.APT_PROCESSOR_JARS_MISSING.equals(w.code()));
        assertFalse(anyAptWarning,
            "APT_PROCESSOR_JARS_MISSING must not fire when no processors were declared; warnings: "
                + service.getWarnings());
    }

    private static void runMaven(String mvnBinary, Path projectRoot, String... goals)
            throws IOException, InterruptedException {
        java.util.List<String> command = new java.util.ArrayList<>();
        command.add(mvnBinary);
        for (String g : goals) command.add(g);
        Process p = new ProcessBuilder(command)
            .directory(projectRoot.toFile())
            .redirectErrorStream(true)
            .start();
        StringBuilder captured = new StringBuilder();
        try (var reader = new java.io.BufferedReader(new java.io.InputStreamReader(p.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (captured.length() < 8192) captured.append(line).append('\n');
            }
        }
        boolean done = p.waitFor(5, TimeUnit.MINUTES);
        if (!done) {
            p.destroyForcibly();
            throw new RuntimeException("mvn " + String.join(" ", goals) + " timed out\n" + captured);
        }
        if (p.exitValue() != 0) {
            throw new RuntimeException("mvn " + String.join(" ", goals)
                + " failed with exit code " + p.exitValue() + "\n" + captured);
        }
    }

    /**
     * Pull the registered container ids out of an {@link IFactoryPath} via reflection.
     * The internal impl is {@code org.eclipse.jdt.apt.core.internal.util.FactoryPath} with
     * a {@code getAllContainers()} method returning {@code Map<FactoryContainer, ...>}, and
     * {@code FactoryContainer.getId()} yields the absolute jar path for external jars. We
     * avoid binding to the internal package directly so the production core bundle's
     * MANIFEST stays clean.
     */
    private static java.util.List<String> factoryPathContainerIds(IFactoryPath factoryPath) {
        try {
            Method getAllContainers = factoryPath.getClass().getMethod("getAllContainers");
            Object result = getAllContainers.invoke(factoryPath);
            if (!(result instanceof Map<?, ?> containers)) {
                throw new AssertionError("getAllContainers returned non-Map: " + result);
            }
            java.util.List<String> ids = new java.util.ArrayList<>();
            for (Object container : containers.keySet()) {
                Method getId = container.getClass().getMethod("getId");
                Object id = getId.invoke(container);
                ids.add(id == null ? null : id.toString());
            }
            return ids;
        } catch (ReflectiveOperationException e) {
            throw new AssertionError("Could not introspect factory path containers — "
                + "JDT internal API may have changed (impl class: "
                + factoryPath.getClass().getName() + ")", e);
        }
    }

    private static String resolveMavenBinary() {
        boolean isWindows = System.getProperty("os.name").toLowerCase().contains("win");
        String binaryName = isWindows ? "mvn.cmd" : "mvn";

        try {
            Process p = new ProcessBuilder(binaryName, "-v").redirectErrorStream(true).start();
            try (var r = new java.io.BufferedReader(new java.io.InputStreamReader(p.getInputStream()))) {
                while (r.readLine() != null) { /* drain */ }
            }
            p.waitFor();
            if (p.exitValue() == 0) return binaryName;
        } catch (IOException | InterruptedException ignored) {
            if (Thread.interrupted()) Thread.currentThread().interrupt();
        }

        Path wrapperDists = Path.of(System.getProperty("user.home"), ".m2", "wrapper", "dists");
        if (!Files.isDirectory(wrapperDists)) return null;
        try (Stream<Path> distros = Files.list(wrapperDists)) {
            for (Path distro : distros.toList()) {
                try (Stream<Path> hashes = Files.list(distro)) {
                    for (Path hashDir : hashes.toList()) {
                        Path bin = hashDir.resolve("bin").resolve(binaryName);
                        if (Files.isRegularFile(bin)) return bin.toString();
                    }
                }
            }
        } catch (IOException ignored) {}
        return null;
    }
}
